P000001: $T_0$ : T0Space
P000002: $T_1$ : T1Space
P000003: $T_2$ : T2Space
P000004: $T_{2 \frac{1}{2}}$ : T25Space
P000005: $T_3$ : T3Space
P000006: $T_{3 \frac{1}{2}}$ : T35Space
P000007: $T_4$ : T4Space
P000008: $T_5$ : T5Space
P000009: Functionally Hausdorff : FunctionallyHausdorffSpace
P000010: Semiregular : SemiregularSpace
P000011: Regular : RegularSpace
P000012: Completely regular : CompletelyRegularSpace
P000013: Normal : NormalSpace
P000014: Completely normal : CompletelyNormalSpace
P000015: Perfectly normal : PerfectlyNormalSpace
P000016: Compact : CompactSpace
P000017: $\sigma$-compact : SigmaCompactSpace
P000018: Lindelöf : LindelofSpace
P000019: Countably compact : CountablyCompactSpace
P000020: Sequentially Compact : SequentiallyCompactSpace
P000021: Weakly Countably Compact : WeaklyCountablyCompactSpace
P000022: Pseudocompact : PseudocompactSpace
P000023: Weakly Locally Compact : WeaklyLocallyCompactSpace
P000024: Locally Relatively Compact : LocallyRelativelyCompactSpace
P000025: Exhaustible by compacts : ExhaustibleByCompactsSpace
P000026: Separable : SeparableSpace
P000027: Second Countable : SecondCountableSpace
P000028: First Countable : FirstCountableSpace
P000029: Countable chain condition : CountableChainConditionSpace
P000030: Paracompact : ParacompactSpace
P000031: Metacompact : MetacompactSpace
P000032: Countably paracompact : CountablyParacompactSpace
P000033: Countably metacompact : CountablyMetacompactSpace
P000034: Fully normal : FullyNormalSpace
P000035: Fully $T_4$ : FullyT4Space
P000036: Connected : ConnectedSpace
P000037: Path Connected : PathConnectedSpace
P000038: Arc connected : ArcConnectedSpace
P000039: Hyperconnected : HyperconnectedSpace
P000040: Ultraconnected : UltraconnectedSpace
P000041: Locally Connected : LocallyConnectedSpace
P000042: Locally Path Connected : LocallyPathConnectedSpace
P000043: Locally Arc Connected : LocallyArcConnectedSpace
P000044: Biconnected : BiconnectedSpace
P000045: Has a Dispersion Point : HasADispersionPointSpace
P000046: Totally Path Disconnected : TotallyPathDisconnectedSpace
P000047: Totally Disconnected : TotallyDisconnectedSpace
P000048: Totally Separated : TotallySeparatedSpace
P000049: Extremally disconnected : ExtremallyDisconnectedSpace
P000050: Zero Dimensional : ZeroDimensionalSpace
P000051: Scattered : ScatteredSpace
P000052: Discrete : DiscreteSpace
P000053: Metrizable : MetrizableSpace
P000054: $\sigma$-Locally Finite Base : SigmaLocallyFiniteBaseSpace
P000055: Completely metrizable : CompletelyMetrizableSpace
P000056: Meager : MeagerSpace
P000057: Countable : CountableSpace
P000058: Cardinality $\lt\mathfrak c$ : CardinalityLtcSpace
P000059: Cardinality $\leq 2^{\mathfrak c}$ : CardinalityLeqPowCSpace
P000060: Strongly Connected : StronglyConnectedSpace
P000061: Cozero complemented : CozeroComplementedSpace
P000062: Weakly Lindelof : WeaklyLindelofSpace
P000063: Čech complete : CechCompleteSpace
P000064: Baire : BaireSpace
P000065: Cardinality $=\mathfrak c$ : CardinalityCSpace
P000066: Menger : MengerSpace
P000067: $T_6$ : T6Space
P000068: Rothberger : RothbergerSpace
P000069: Strategic Menger : StrategicMengerSpace
P000070: Markov Menger : MarkovMengerSpace
P000071: $\sigma$-relatively-compact : SigmaRelativelyCompactSpace
P000072: 2-Markov Menger : 2MarkovMengerSpace
P000073: Sober : SoberSpace
P000074: Cosmic : CosmicSpace
P000075: Spectral space : SpectralSpace
P000076: Proximal : ProximalSpace
P000077: Corson compact : CorsonCompactSpace
P000078: Finite : FiniteSpace
P000079: Sequential : SequentialSpace
P000080: Fréchet Urysohn : FrechetUrysohnSpace
P000081: Countably tight : CountablyTightSpace
P000082: Locally metrizable : LocallyMetrizableSpace
P000084: Locally Hausdorff : LocallyHausdorffSpace
P000085: Ascoli : AscoliSpace
P000086: Homogeneous : HomogeneousSpace
P000087: Has a group topology : HasAGroupTopologySpace
P000088: Collectionwise normal : CollectionwiseNormalSpace
P000089: Fixed Point Property : FixedPointPropertySpace
P000090: Alexandrov : AlexandrovSpace
P000091: Eberlein compact : EberleinCompactSpace
P000092: Moving Off Property : MovingOffPropertySpace
P000093: Locally countable : LocallyCountableSpace
P000095: I-tactic Banach-Mazur : ITacticBanachMazurSpace
P000096: II-tactic Banach-Mazur : IiTacticBanachMazurSpace
P000097: Homotopy Dense : HomotopyDenseSpace
P000098: Generated by countably-many compacts : GeneratedByCountablyManyCompactsSpace
P000099: US : UsSpace
P000100: KC : KcSpace
P000101: Has closed retracts : HasClosedRetractsSpace
P000103: Strongly KC : StronglyKcSpace
P000104: K Analytic : KAnalyticSpace
P000105: Angelic : AngelicSpace
P000106: Strictly Angelic : StrictlyAngelicSpace
P000110: Has A Compact Resolution : HasACompactResolutionSpace
P000111: Hemicompact : HemicompactSpace
P000112: Submetrizable : SubmetrizableSpace
P000113: k$\mathbb{R}$ Space : K\Mathbb{R}Space
P000114: Cardinality $=\aleph_1$ : CardinalityAleph1Space
P000115: Weakly K Analytic : WeaklyKAnalyticSpace
P000116: Polish : PolishSpace
P000118: Pseudo-Polish : PseudoPolishSpace
P000119: Z-Compact : ZCompactSpace
P000121: Pseudometrizable : PseudometrizableSpace
P000122: S space : SSpace
P000123: Locally $n$-Euclidean : LocallyNEuclideanSpace
P000124: Topological $n$-manifold : TopologicalNManifoldSpace
P000125: Has multiple points : HasMultiplePointsSpace
P000126: Door : DoorSpace
P000127: Dowker : DowkerSpace
P000128: $k$-Lindelöf : KLindelofSpace
P000129: Indiscrete : IndiscreteSpace
P000130: Locally Compact : LocallyCompactSpace
P000131: Hereditarily Lindelöf : HereditarilyLindelofSpace
P000132: $G_\delta$ space : GdeltaSpace
P000133: LOTS : LotsSpace
P000134: $R_1$ : R1Space
P000135: $R_0$ : R0Space
P000136: Anticompact : AnticompactSpace
P000137: Empty : EmptySpace
P000138: Countably-many continuous self-maps : CountablyManyContinuousSelfMapsSpace
P000139: Has an isolated point : HasAnIsolatedPointSpace
P000140: Generated by compact subspaces : GeneratedByCompactSubSpacesSpace
P000141: Generated by maps from compact Hausdorff spaces : GeneratedByMapsFromCompactHausdorffSpacesSpace
P000142: Generated by compact Hausdorff subspaces : GeneratedByCompactHausdorffSubSpacesSpace
P000143: Weak Hausdorff : WeakHausdorffSpace
P000144: Locally pseudometrizable : LocallyPseudometrizableSpace
P000145: Strongly paracompact : StronglyParacompactSpace
P000146: Ultraparacompact : UltraparacompactSpace
P000147: P-space : PSpace
P000148: CGWH : CgwhSpace
P000149: $\varepsilon$-space : EpsilonSpace
P000150: $\omega$-Rothberger : OmegaRothbergerSpace
P000151: Strategically Rothberger : StrategicallyRothbergerSpace
P000152: Markov Rothberger : MarkovRothbergerSpace
P000153: $\omega$-Menger : OmegaMengerSpace
P000156: $k$-Rothberger : KRothbergerSpace
P000157: Strategically $k$-Rothberger : StrategicallyKRothbergerSpace
P000158: Markov $k$-Rothberger : MarkovKRothbergerSpace
P000159: $k$-Menger : KMengerSpace
P000160: Strategically $k$-Menger : StrategicallyKMengerSpace
P000161: Markov $k$-Menger : MarkovKMengerSpace
P000162: Realcompact : RealcompactSpace
P000163: Cardinality $\leq\mathfrak c$ : CardinalityLeqcSpace
P000164: Non-measurable cardinality : NonMeasurableCardinalitySpace
P000165: Pseudonormal : PseudonormalSpace
P000166: Has a coarser separable metrizable topology : HasACoarserSeparableMetrizableTopologySpace
P000167: Sequentially discrete : SequentiallyDiscreteSpace
P000168: $\omega$C : OmegacSpace
P000169: Semi-Hausdorff : SemiHausdorffSpace
P000170: $k_1$-Hausdorff : K1HausdorffSpace
P000171: $k_2$-Hausdorff : K2HausdorffSpace
P000172: Radial : RadialSpace
P000173: Pseudoradial : PseudoradialSpace
P000174: Well-based : WellBasedSpace
P000175: Cardinality $\geq 3$ : CardinalityGeq3Space
P000176: Cardinality $\geq 4$ : CardinalityGeq4Space
P000177: $\sigma$-space : SigmaSpace
P000178: $\aleph$-space : AlephSpace
P000179: $\aleph_0$-space : Aleph0Space
P000180: Hereditarily separable : HereditarilySeparableSpace
